
USE [master]
GO

/****** Object:  Database [RedXproject]    Script Date: 15/01/2017 19:52:45 ******/
CREATE DATABASE [RedXproject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RedXproject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RedXproject.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RedXproject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RedXproject_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RedXproject] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RedXproject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RedXproject] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [RedXproject] SET ANSI_NULLS OFF
GO

ALTER DATABASE [RedXproject] SET ANSI_PADDING OFF
GO

ALTER DATABASE [RedXproject] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [RedXproject] SET ARITHABORT OFF
GO

ALTER DATABASE [RedXproject] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [RedXproject] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [RedXproject] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [RedXproject] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [RedXproject] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [RedXproject] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [RedXproject] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [RedXproject] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [RedXproject] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [RedXproject] SET  DISABLE_BROKER
GO

ALTER DATABASE [RedXproject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [RedXproject] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [RedXproject] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [RedXproject] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [RedXproject] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [RedXproject] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [RedXproject] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [RedXproject] SET RECOVERY FULL
GO

ALTER DATABASE [RedXproject] SET  MULTI_USER
GO

ALTER DATABASE [RedXproject] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [RedXproject] SET DB_CHAINING OFF
GO

ALTER DATABASE [RedXproject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [RedXproject] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [RedXproject] SET DELAYED_DURABILITY = DISABLED
GO

USE [RedXproject]
GO

/****** Object:  Table [dbo].[LogTable]    Script Date: 15/01/2017 19:52:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[textTable]    Script Date: 15/01/2017 19:52:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

USE [master]
GO

ALTER DATABASE [RedXproject] SET  READ_WRITE
GO
